POST http://localhost:3000/follower/accept/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImZpcnN0TmFtZSI6Ik5hem1hIiwibGFzdE5hbWUiOiJOYXphciIsImVtYWlsIjoibmF6bWFuYXphcjVAZ21haWwuY29tIiwiaWF0IjoxNjk3ODI3MTQwLCJleHAiOjE3MDA0MTkxNDB9.aN8epSP6oI6NkDo9DYemQzZ8E6LvKKX9lhUfKZlzgvk