POST http://localhost:3000/vendor/addToCart/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBnbWFpbC5jb20iLCJpYXQiOjE2OTc0NTc2OTksImV4cCI6MTcwMDA0OTY5OX0.KWG6YrANmTqrcB558Jiv2BTzU6iaPhDPeCs8q6gK2Rs

{
    "Quantity" : 1
}