POST http://localhost:3000/vendor/addToCheckout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkdhZ2lpIiwibGFzdE5hbWUiOiJQZXJlcmEiLCJlbWFpbCI6ImdhZ2lpQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY1OTQ5OSwiZXhwIjoxNzAxMjUxNDk5fQ.AkW0GVMRIHACkhfF8l7bjxdt9YefILuTC9CY3nP_zNM