POST http://localhost:3000/trip
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImZpcnN0TmFtZSI6IlRlc3QiLCJsYXN0TmFtZSI6IlVzZXIiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjk4NTgwOTAzLCJleHAiOjE3MDExNzI5MDN9.E3L7PpHQL3qUOaMhQNpQIS-pl-LaKDjG2uaNqCCufzA

{
    "startDate":"10/29/2023",
    "numberOfDays": "3",
    "startPlace": "Galle",
    "category": "Private"
}