POST http://localhost:3000/trip/budget HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkFtYXNoaSIsImxhc3ROYW1lIjoiU2FuZHVuaSIsImVtYWlsIjoiYW1hc2hpQGdtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2OTg3NDA2MjIsImV4cCI6MTcwMTMzMjYyMn0.ifmeCVyapr2wx18c9jiCYYYLYEJy4PPl92rSy_zK5u4

{
  "tripId": 18,
  "expenses": [
    {
      "category": "food",
      "expense_name": "Lunch",
      "amount": 500.00,
      "date" : "10/10/2023"
    },
    {
      "category": "transport",
      "expense_name": "Taxi",
      "amount": 100.00,
      "date" : "10/10/2023"
    }
  ]
}
