GET  http://localhost:3000/trip/activity/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoibHVxbWFuX2Z6QGVtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJpYXQiOjE2OTQ4NDMyNDIsImV4cCI6MTY5NDg0Njg0Mn0.N0eMFcarUQJM5ENK8DEnKycrT_bCq9rDNnOzaW6ds5o