GET http://localhost:3000/user/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IlNhY2hpbmkiLCJsYXN0TmFtZSI6IlVzaGEiLCJlbWFpbCI6ImFtYXNoaUBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjk4ODA5NTY0LCJleHAiOjE3MDE0MDE1NjR9.SX5ruuJ6JwY9t5xWc7xffPGtXJxgwA41NMFqsgUUaxE