GET http://localhost:3000/trip/budget/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoibHVxbWFuX2Z6QGVtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJpYXQiOjE2OTQzNTA4NjQsImV4cCI6MTY5NDM1NDQ2NH0.83Chy7RYqF9PFr3tThDpCWz-6jQfxtIgQ43hasSLMPc