GET http://localhost:3000/trip/currentTrips HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkFtYXNoaSIsImxhc3ROYW1lIjoiU2FuZHVuaSIsImVtYWlsIjoiYW1hc2hpQGdtYWlsLmNvbSIsImlhdCI6MTY5ODYwOTMzOSwiZXhwIjoxNzAxMjAxMzM5fQ.cbkti8aYRFq34CbbOCbN2d9R2odmPHie318-tSw1GqQ