GET http://localhost:3000/admin/viewComplaint/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjk4NjQzODU5LCJleHAiOjE3MDEyMzU4NTl9._0oCTQcb5BztICKztxvoU_t-gHrNEic3EHO0pOLBmSw
