GET http://localhost:3000/vendor/getDeliveryMethod?delivery_method=DHL HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkdhZ2lpIiwibGFzdE5hbWUiOiJQZXJlcmEiLCJlbWFpbCI6ImdhZ2lpQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY1ODEzMiwiZXhwIjoxNzAxMjUwMTMyfQ.kGegyVH6tWE962xHM-Q9qdbWcBGPsGnAW4FO1u1YjXE
