GET http://localhost:3000/user/followingCount HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBnbWFpbC5jb20iLCJpYXQiOjE2OTgzNDA3MDksImV4cCI6MTcwMDkzMjcwOX0.qxjik7OtDP48l_D-pefs3FSbcXlcOSiiH0xus5Q5EaI