GET http://localhost:3000/follower/followers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBnbWFpbC5jb20iLCJpYXQiOjE2OTc4Mjk4MjMsImV4cCI6MTcwMDQyMTgyM30.MvIGDTYP6KuWra5GoWH3pZHDkhPQ1eGxN7LMvyOxt4M