GET http://localhost:3000/user/getPoints HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkFtYXNoaSIsImxhc3ROYW1lIjoiU2FuZHVuaSIsImVtYWlsIjoiYW1hc2hpQGdtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2OTg4MTQ1NjQsImV4cCI6MTcwMTQwNjU2NH0.SyLSnWIkWx41jdj0ti1x-QUJxDSP27739XhVGGIcwkk