GET http://localhost:3000/vendor/getOrderAmount HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6IkdhZ2lpIiwibGFzdE5hbWUiOiJQZXJlcmEiLCJlbWFpbCI6ImdhZ2lpQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY1NDYzNCwiZXhwIjoxNzAxMjQ2NjM0fQ._ISf89YxDCnMPo_6zJKjI-omASzwRpCK6TTej1SONtQ