GET http://localhost:3000/trip/public/mates/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjk4NjYxNTkyLCJleHAiOjE3MDEyNTM1OTJ9.PdjOELgIC8BPQIyrh_NHRk9UUjL3BFSjlr9EBDfyqlk
