GET http://localhost:3000/trip/public/mates/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImZpcnN0TmFtZSI6IlRlc3QiLCJsYXN0TmFtZSI6IlVzZXIiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjk4Mzk5NDU0LCJleHAiOjE3MDA5OTE0NTR9.yGqSHVAE4txCHhWo0j3dfyo3ZvVEUC5DCetzCz8yX2o
