GET http://localhost:3000/user/myPosts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjk4NzMyMzc0LCJleHAiOjE3MDEzMjQzNzR9.rpCA50KV-6RYBlC6XxJFJkhOWF_NDlRRwMhVEzBziYc