GET http://localhost:3000/user/myPosts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6ImhhbnNhbmEiLCJsYXN0TmFtZSI6ImthdmlzaGthIiwiZW1haWwiOiJhbWFzaGlAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY5ODgxNjMwNiwiZXhwIjoxNzAxNDA4MzA2fQ.qF7v4gwgeh2Q8hfd22-7lmzE9_nL7A9vqQnMNfIuHOY