GET http://localhost:3000/user/myProfile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkFtYXNoaSIsImxhc3ROYW1lIjoiU2FuZHVuaSIsImVtYWlsIjoiYW1hc2hpQGdtYWlsLmNvbSIsImlhdCI6MTY5ODUxOTk1NywiZXhwIjoxNzAxMTExOTU3fQ.V2HslkgNFhx-O6iUkSPg4WyqGoBMRYewnfUSfK6zPeo