GET http://localhost:3000/trip/myTrips HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBlbWFpbC5jb20iLCJpYXQiOjE2OTQ3NzEyMDUsImV4cCI6MTY5NzM2MzIwNX0.saTQe7UGTSrxkJcbJeShu2KdEyhtTYTB-2aJLYIwIEU