POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "trinee",
  "email": "trinee@gmail.com",
  "password": "trinee",
  "firstName": "Trineesha",
  "lastName": "Sanduni",
  "birthday": "2000-05-29",
  "gender": "Female",
  "phoneNo": "1129623584"
}