POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "thotSlayer",
  "email": "luqman_fz@gmail.com",
  "password": "abc123",
  "firstName": "Luqman",
  "lastName": "Fazal",
  "birthday": "2000-05-29",
  "gender": "Male",
  "phoneNo": "0767716157"
}