GET http://localhost:3000/search/myProducts?assential_name=tent HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBnbWFpbC5jb20iLCJpYXQiOjE2OTcyNzY5NDgsImV4cCI6MTY5OTg2ODk0OH0.5xgy3r9weVenjmwZ98ink3Y7EtEq4x_Kh0YRAzLUtao