GET http://localhost:3000/search?userQuery=hik HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJlbWFpbCI6Imx1cW1hbl9mekBlbWFpbC5jb20iLCJpYXQiOjE2OTUzNjI5ODksImV4cCI6MTY5Nzk1NDk4OX0.nw_hZ4QaMi4ND06UcwycxWxIlV0_iDwgY2KdnaJjFkM