GET http://localhost:3000/trip HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoibHVxbWFuX2Z4QGVtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImlhdCI6MTY5NDIzNjM0MSwiZXhwIjoxNjk0MjM5OTQxfQ.9-sy3P4X5-EKfE6JcKwTVWOISD4Xq8CYid3OdpGbU3E