GET http://localhost:3000/trip/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoibHVxbWFuX2Z4QGVtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImlhdCI6MTY5NDI1NzMwMCwiZXhwIjoxNjk0MjYwOTAwfQ.FS5FH112cfKe8GmoXo_vBZKMWLB-jqmUn3LyXP-C53U