PUT http://localhost:3000/trip/budget HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoiTHVxbWFuIiwibGFzdE5hbWUiOiJGYXphbCIsImVtYWlsIjoibHVxbWFuX2Z6QGdtYWlsLmNvbSIsImlhdCI6MTY5NDQyMzQ2NywiZXhwIjoxNjk3MDE1NDY3fQ.IaJhVURWC9elb-gu0pH6i00qMNG2RzlWFssiAoS0yyU

{
    "budget": {
        "id": 11
    },
  "expenses": [
    {
      "expense_name": "Taxi",
      "amount": 1001,
      "category": "Transportation"
    },
    {
      "expense_name": "Hotel fare",
      "amount": 5000,
      "category": "Accomodation"
    }
  ]
}