PUT http://localhost:3000/user/update_password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6IkJ1ZGRpIiwibGFzdE5hbWUiOiJZYXBhIiwiZW1haWwiOiJzYWNoaW5pLnVzaGFAZ21haWwuY29tIiwiaWF0IjoxNjk0ODg2MjQzLCJleHAiOjE2OTc0NzgyNDN9.YUtax5pXu7Kptq_YbrL59Uni_gLj0mHZCLZexW6nazs

{
    "newPassword":"BudhdhiYapa"
}