PUT http://localhost:3000/trip/budget/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoibHVxbWFuX2Z6QGVtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1cW1hbiIsImxhc3ROYW1lIjoiRmF6YWwiLCJpYXQiOjE2OTQzNTgzNzksImV4cCI6MTY5NDM2MTk3OX0.RZOIzCIjpX-xJjarzSGoCYfHrzRJdL4UCtD-CErtD9M

{
    "budget": {
        "id": 8
    },
  "expenses": [
    {
      "expense_name": "Taxi",
      "amount": 500,
      "category": "Transportation"
    },
    {
      "expense_name": "Hotel fare",
      "amount": 5000,
      "category": "Accomodation"
    }
  ]
}