GET http://localhost:3000/user/viewComments/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImZpcnN0TmFtZSI6Ik5hem1hIiwibGFzdE5hbWUiOiJOYXphciIsImVtYWlsIjoibmF6bWFuYXphcjVAZ21haWwuY29tIiwiaWF0IjoxNjk1NjYxNzc5LCJleHAiOjE2OTgyNTM3Nzl9.q5rQVkXDzLmXh0Xwd1M0FAxN3cxylbSk8JK5JEG_h7o