GET http://localhost:3000/user/myProfile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImZpcnN0TmFtZSI6IlNld3dhbmRpIiwibGFzdE5hbWUiOiJXaWNrcmFtYXJhdGhuYSIsImVtYWlsIjoic2FjaGluaS51c2hhQGdtYWlsLmNvbSIsImlhdCI6MTY5NDg2MDM5OSwiZXhwIjoxNjk3NDUyMzk5fQ.UAC4S8cFiBPohLnQu-Q8OvX1OtZ_tjcwwJaiUm-WqNA